### ISSUE TITLE
visibility issue

### ISSUE THREAD

**Issue by Amir132ss** [Amir132ss/amirreposi#3]
- [ ] issue_01  cant see logging button #3
- [ ] issue_02   cant see password text field #3
- [ ] issue_03 cant see failed status #3
